# These are supported funding model platforms

patreon: brenoprata
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5FCW8E52Y6LZ4&source=url', 'https://pag.ae/7UBETN22L']
